apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello-world
        image: dockerregistry.arcticlake.com/hello-world
        ports:
        - name: http-port
          containerPort: 8080
