apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: build-registry-proxy
spec:
  selector:
    matchLabels:
      k8s-app: build-registry-proxy
  template:
    metadata:
      labels:
        k8s-app: build-registry-proxy
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
        env:
        - name: REGISTRY_HOST
          value: build-registry
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000